<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Dapper" Version="2.1.66" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="10.0.9" />
	<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Sporeo.BuildingBlocks.Infrastructure.Persistence\Sporeo.BuildingBlocks.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Sporeo.BuildingBlocks.Infrastructure.Messaging\Sporeo.BuildingBlocks.Infrastructure.Messaging.csproj" />
    <ProjectReference Include="..\Sporeo.Fixtures.Application\Sporeo.Fixtures.Application.csproj" />
    <ProjectReference Include="..\Sporeo.Fixtures.Domain\Sporeo.Fixtures.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sporeo.Fixtures.Infrastructure.Persistence.Tests" />
  </ItemGroup>

</Project>
