<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sporeo.Fixtures.Application\Sporeo.Fixtures.Application.csproj" />
    <ProjectReference Include="..\Sporeo.Fixtures.Infrastructure.Integration\Sporeo.Fixtures.Infrastructure.Integration.csproj" />
    <ProjectReference Include="..\Sporeo.Fixtures.Infrastructure.Persistence\Sporeo.Fixtures.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Sporeo.BuildingBlocks.Infrastructure\Sporeo.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Platform\Sporeo.ServiceDefaults\Sporeo.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Quartz.Extensions.Hosting" />
    <PackageReference Include="Quartz.Serialization.Json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sporeo.Fixtures.Worker.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripts\quartz_schema.sql" />
  </ItemGroup>

</Project>
